allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  bcrypt: true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
  vue-demi: true
overrides:
  ai: $ai
minimumReleaseAgeExclude:
  - '@tiptap/extension-placeholder@3.29.1'
  - '@tiptap/extensions@3.29.1'
