<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900 flex flex-col">
    <!-- Simple Header -->
    <header class="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <NuxtLink to="/" class="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <UIcon name="i-lucide-zap" class="w-6 h-6 text-primary-500" />
            <span class="font-bold text-lg text-gray-900 dark:text-white">Coach Wattz</span>
          </NuxtLink>
          <div class="flex items-center gap-4">
            <UButton to="/" color="primary" variant="soft" size="sm"> Try Coach Wattz </UButton>
            <ColorModeButton />
          </div>
        </div>
      </div>
    </header>

    <main class="flex-1">
      <slot />

      <SharePageCTA />
    </main>

    <!-- Footer -->
    <footer
      class="mt-auto py-12 px-6 border-t border-gray-200 dark:border-gray-700 text-center bg-white dark:bg-gray-800"
    >
      <p class="text-sm text-gray-500 dark:text-gray-400">
        Generated by
        <a href="https://coachwatts.com/" class="font-bold text-primary-500 hover:underline"
          >Coach Wattz</a
        >
      </p>
      <p class="text-xs text-gray-400 dark:text-gray-500 mt-2">
        Personalized AI Endurance Coaching
      </p>
    </footer>
  </div>
</template>
